// SPDX-License-Identifier: GPL-3.0-or-later
#include "fingerprint.h"
#include "tls_ctx.h"
#include "../common/platform.h"
#include "../common/util.h"
#include "../common/config.h"
#include "../common/tspu.h"
#include "../net/tcp.h"

#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/rand.h>

#include <chrono>
#include <algorithm>
#include <cstdlib>
#include <cstring>

using std::string;

namespace {
HttpsProbe plain_http_exchange(const string& host, int port, const string& request) {
    HttpsProbe r;
    string err;
    SOCKET socket = tcp_connect(host, port, g_tcp_to, err);
    if (socket == INVALID_SOCKET) { r.err = err; return r; }
    const bool sent = tcp_send_all(socket, request.data(), static_cast<int>(request.size())) == static_cast<int>(request.size());
    string bytes;
    if (sent) {
        const auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(1500);
        char buffer[1024];
        while (bytes.size() < HTTPS_HEADER_LIMIT) {
            const auto left = std::chrono::duration_cast<std::chrono::milliseconds>(deadline - std::chrono::steady_clock::now()).count();
            if (left <= 0) break;
            const int n = tcp_recv_to(socket, buffer, static_cast<int>(std::min(sizeof(buffer), HTTPS_HEADER_LIMIT - bytes.size())), static_cast<int>(left));
            if (n <= 0) break;
            bytes.append(buffer, n);
            r = parse_https_response(bytes);
            if (r.http_valid || (!r.err.empty() && r.err.rfind("incomplete", 0) != 0)) break;
        }
    }
    closesocket(socket);
    r = parse_https_response(bytes);
    r.request_sent = sent;
    if (!sent) r.err = "HTTP request write failed";
    return r;
}
}

FpResult fp_http_plain(const string& host, int port) {
    const auto authority = http_authority(host, port, 80);
    if (authority.empty()) { FpResult f; f.service = "HTTP?"; f.details = "invalid HTTP authority"; return f; }
    return http_fingerprint_response(plain_http_exchange(host, port,
        "GET / HTTP/1.1\r\nHost: " + authority + "\r\nAccept: */*\r\nConnection: close\r\n\r\n"));
}

FpResult fp_ssh(const string& banner_hint, const string& host, int port) {
    FpResult f; f.service = "SSH?";
    string b = banner_hint;
    if (b.empty() || b.substr(0, 4) != "SSH-") {
        string err; SOCKET s = tcp_connect(host, port, g_tcp_to, err);
        if (s != INVALID_SOCKET) {
            char buf[256]; int n = tcp_recv_to(s, buf, sizeof(buf) - 1, 1500);
            closesocket(s);
            if (n > 0) { buf[n] = 0; b.assign(buf, n); }
        }
    }
    if (b.substr(0, 4) == "SSH-") {
        f.service = "SSH";
        while (!b.empty() && (b.back() == '\r' || b.back() == '\n')) b.pop_back();
        f.details = b;
    } else {
        f.details = "no SSH banner (but port open)";
    }
    return f;
}

FpResult fp_socks5(const string& host, int port) {
    FpResult f; f.service = "SOCKS?";
    string err; SOCKET s = tcp_connect(host, port, g_tcp_to, err);
    if (s == INVALID_SOCKET) { f.silent = true; f.details = "no connect (" + err + ")"; return f; }
    unsigned char greet[] = {0x05, 0x02, 0x00, 0x02};
    tcp_send_all(s, greet, sizeof(greet));
    unsigned char reply[4]; int n = tcp_recv_to(s, (char*)reply, 2, 1200);
    f.end = classify_recv(n, n < 0 ? WSAGetLastError() : 0);
    if (n == 1) {
        int more = tcp_recv_to(s, (char*)reply + 1, 1, 1200);
        if (more == 1) ++n;
    }
    closesocket(s);
    f.outcome = socks5_reply_outcome(reply, n, f.end);
    if (n <= 0) { f.silent = true; f.details = read_end_name(f.end); return f; }
    if (f.outcome == Outcome::Positive) {
        f.service = "SOCKS5";
        f.details = "methods=0x" + hex_s(reply + 1, 1);
        if      (reply[1] == 0x00) f.details += " (no-auth)";
        else if (reply[1] == 0x02) f.details += " (user/pass)";
        else                       f.details += " (no acceptable method)";
        f.is_vpn_like = true;
    } else {
        f.details = "not SOCKS5, reply=" + hex_s(reply, std::min(2, n));
    }
    return f;
}

FpResult fp_http_connect(const string& host, int port) {
    return http_fingerprint_response(plain_http_exchange(host, port,
        "CONNECT example.com:443 HTTP/1.1\r\nHost: example.com:443\r\n\r\n"), true);
}

FpResult fp_shadowsocks(const string& host, int port) {
    FpResult f; f.service = "SS?";
    string err; SOCKET s = tcp_connect(host, port, g_tcp_to, err);
    if (s == INVALID_SOCKET) { f.silent = true; return f; }
    // 64 truly-random bytes via openssl csprng - not rand()/time() seeded.
    // a deterministic lcg would leak "generated by tool at ~time T".
    unsigned char rnd[64];
    RAND_bytes(rnd, 64);
    tcp_send_all(s, rnd, 64);
    char buf[256]; int n = tcp_recv_to(s, buf, sizeof(buf), 800);
    f.end = classify_recv(n, n < 0 ? WSAGetLastError() : 0);
    closesocket(s);
    // aead servers and ordinary ones look alike here
    if (n <= 0) {
        f.service = "no-reply";
        f.details = string("64 random bytes: ") + read_end_name(f.end) +
                    " within 800 ms; protocol not identified";
    } else {
        f.details = "responded " + std::to_string(n) + "B: " + printable_prefix(string(buf, n));
    }
    return f;
}

FpResult sstp_probe(const string& host, int port, const string& sni) {
    const auto authority = http_authority(sni.empty() ? host : sni, port);
    if (authority.empty()) { FpResult f; f.service = "SSTP?"; f.details = "invalid HTTP authority"; return f; }
    unsigned char guid[16];
    RAND_bytes(guid, sizeof(guid));
    const auto response = https_exchange(host, port, sni, sstp_setup_request(authority, guid), 5000);
    return sstp_response(response);
}
