[Interface]
PrivateKey = QFV2example_private_key_base64_here=
Address = 10.7.0.2/24
DNS = 1.1.1.1
ListenPort = 51820

[Peer]
PublicKey = pubkeyExampleBase64Here=
Endpoint = 203.0.113.10:51820
AllowedIPs = 0.0.0.0/0
