# SPDX-License-Identifier: GPL-3.0-or-later
"""Refresh the embedded PSL from the official distribution URL, or a local copy."""

import argparse
import hashlib
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
URL = "https://publicsuffix.org/list/public_suffix_list.dat"


def render(data):
    rules = set()
    for line in data.decode("utf-8").splitlines():
        rule = line.split("//", 1)[0].strip()
        if not rule:
            continue
        prefix = "!" if rule.startswith("!") else ""
        rule = rule.removeprefix("!")
        labels = [s if s.isascii() else "xn--" + s.encode("punycode").decode("ascii")
                  for s in rule.lower().split(".")]
        encoded = prefix + ".".join(labels)
        if any(c not in "abcdefghijklmnopqrstuvwxyz0123456789-.*!" for c in encoded):
            raise ValueError("unexpected character in PSL rule")
        rules.add(encoded)
    if not {"com", "co.uk", "*.ck", "!www.ck", "github.io", "workers.dev"} <= rules:
        raise ValueError("incomplete PSL input")
    digest = hashlib.sha256(data).hexdigest()
    header = ("// SPDX-License-Identifier: MPL-2.0\n"
              "// This Source Code Form is subject to the terms of the Mozilla Public\n"
              "// License, v. 2.0. If a copy of the MPL was not distributed with this\n"
              "// file, You can obtain one at https://mozilla.org/MPL/2.0/.\n"
              "// derived from publicsuffix.org; license and original list in third_party/psl\n"
              "// generated by tools/update_public_suffix.py; edit the source list instead\n"
              f"// source sha256: {digest}\n")
    return header + "".join(f'    "{r}",\n' for r in sorted(rules))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, help="use a local PSL instead of downloading")
    parser.add_argument("--check", action="store_true", help="check generation without writing")
    args = parser.parse_args()
    source = ROOT / "third_party/psl/public_suffix_list.dat"
    if args.source or args.check:
        data = (args.source or source).read_bytes()
    else:
        with urlopen(URL, timeout=30) as response:
            data = response.read(2 * 1024 * 1024 + 1)
    if len(data) > 2 * 1024 * 1024:
        raise ValueError("PSL exceeds 2 MiB")
    output = ROOT / "src/scan/public_suffix_data.inc"
    rendered = render(data)
    if args.check:
        if output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("embedded PSL is out of date")
        print("embedded PSL matches the source snapshot")
        return
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_bytes(data)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"PSL updated; source sha256: {hashlib.sha256(data).hexdigest()}")


if __name__ == "__main__":
    main()
